# -*- coding: utf-8 -*-
"""
build_rmsf_pdbs.py —— 基于 RMSF/avgpos dat 文件生成可视化 PDB
用于绕开 VMD 1.9.3 Win32 的 animate write pdb 静默写入 bug
  - 读取 YASARA 完整 PDB, 提取蛋白 CA 行
  - 按顺序叠加 .atom.dat(RMSF) / .avgpos.dat(平均坐标)
  - 写出 complex_rmsf_rmsf.pdb (B-factor = RMSF) 和 complex_rmsf_average.pdb
"""
import sys
from pathlib import Path

PDB_IN   = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("complex00000.pdb")
ATOM_DAT = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("complex_rmsf.atom.dat")
AVG_DAT  = Path(sys.argv[3]) if len(sys.argv) > 3 else Path("complex_rmsf.avgpos.dat")
PDB_BETA = Path(sys.argv[4]) if len(sys.argv) > 4 else Path("complex_rmsf_rmsf.pdb")
PDB_AVG  = Path(sys.argv[5]) if len(sys.argv) > 5 else Path("complex_rmsf_average.pdb")


def extract_ca_lines(pdb_path: Path):
    """从完整 PDB 中提取蛋白 CA 行（标准 PDB 列宽）。返回字典列表。"""
    rows = []
    with open(pdb_path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if not line.startswith(("ATOM  ", "HETATM")):
                continue
            atom_name = line[12:16].strip()
            if atom_name != "CA":
                continue
            resname = line[17:20].strip()
            # 只保留蛋白残基（VMD 'protein' 关键词识别的命名: 3字母 + CHARMM 变体）
            if resname not in (
                "ALA","ARG","ASN","ASP","CYS","GLN","GLU","GLY","HIS","ILE",
                "LEU","LYS","MET","PHE","PRO","SER","THR","TRP","TYR","VAL",
                "HID","HIE","HIP","CYX","CYM","CSD","HSE","HSD","HSP",
            ):
                continue
            rows.append({
                "raw"     : line,
                "serial"  : int(line[6:11]),
                "name"    : atom_name,
                "resname" : resname,
                "chain"   : line[21:22],
                "resid"   : int(line[22:26]),
                "x"       : float(line[30:38]),
                "y"       : float(line[38:46]),
                "z"       : float(line[46:54]),
                "occ"     : float(line[54:60]) if line[54:60].strip() else 1.00,
                "beta"    : float(line[60:66]) if line[60:66].strip() else 0.00,
                "element" : line[76:78].strip() if len(line) >= 78 else "",
                "charge"  : line[78:80] if len(line) >= 80 else "  ",
            })
    return rows


def load_dat(path: Path, ncols_last: int = 1):
    """读取 dat 文件, 返回最后一列(float)的有序列表。"""
    vals = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            try:
                vals.append(float(parts[-ncols_last]) if ncols_last == 1
                            else [float(p) for p in parts[-ncols_last:]])
            except ValueError:
                continue
    return vals


def write_pdb(rows, coords, betas, out_path: Path, tag: str):
    """按 PDB 标准列宽写出文件。"""
    n = len(rows)
    assert len(coords) == n, f"{tag}: coords({len(coords)}) != rows({n})"
    assert len(betas)  == n, f"{tag}: betas({len(betas)}) != rows({n})"
    serial = 1
    out_lines = [f"REMARK Generated by build_rmsf_pdbs.py ({tag})",
                 f"REMARK {n} CA atoms"]
    for r, (x, y, z), b in zip(rows, coords, betas):
        # 复用原 line 的 name/resname/chain/resid, 替换 x/y/z/beta, 重新编号 serial
        name    = r["name"]
        resname = r["resname"]
        chain   = r["chain"] or "X"
        resid   = r["resid"]
        occ     = r["occ"]
        element = r["element"] or " C"
        # 关键字段按 PDB 标准列宽对齐
        line = (f"ATOM  {serial:5d} {name:<4s} {resname:>3s} {chain:1s}"
                f"{resid:4d}    {x:8.3f}{y:8.3f}{z:8.3f}{occ:6.2f}{b:6.2f}"
                f"          {element:>2s}{r['charge']:2s}")
        out_lines.append(line)
        serial += 1
    out_lines.append("END")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out_lines) + "\n")
    print(f"[OK] {out_path} ({n} CA atoms)")


def main():
    print(f"PDB    : {PDB_IN}")
    print(f"ATOMDAT: {ATOM_DAT}")
    print(f"AVGDAT : {AVG_DAT}")

    rows = extract_ca_lines(PDB_IN)
    print(f"提取 CA 行: {len(rows)}")

    rmsfs = load_dat(ATOM_DAT, ncols_last=1)
    avgs  = load_dat(AVG_DAT,  ncols_last=3)
    print(f"RMSF  值数: {len(rmsfs)}")
    print(f"AVG  坐标数: {len(avgs)}")

    if not (len(rows) == len(rmsfs) == len(avgs)):
        print("[WARN] 三个文件行数不完全一致! 写出时按最短截断。",
              file=sys.stderr)
    n = min(len(rows), len(rmsfs), len(avgs))
    rows, rmsfs, avgs = rows[:n], rmsfs[:n], avgs[:n]

    # 原始坐标（用作 rmsf.pdb 骨架，beta = RMSF 用于着色）
    orig_coords = [(r["x"], r["y"], r["z"]) for r in rows]
    write_pdb(rows, orig_coords, rmsfs, PDB_BETA, "B-factor=RMSF")

    # 平均结构（坐标用 mean，beta 用 RMSF）
    write_pdb(rows, avgs, rmsfs, PDB_AVG, "average coords, beta=RMSF")


if __name__ == "__main__":
    main()
